### ISSUE TITLE
功能性问题，需要解答或其他回答

### ISSUE THREAD

**Issue by BreakFaith01** [xiaojieonly/Ehviewer_CN_SXJ#1053]
现在图片搜索无论如何都搜索不到任何东西了（哪怕是我从刚下载的画廊里面复制粘贴上去的，都没有）
一律显示什么都没有找到
![Screenshot_20240220_171715](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136130966/93e569bb-fce3-43c2-a551-e9ec80716d69)

**Comment by xiaojieonly** [comment]
我看看

**Comment by Pitohui-Dichrous** [comment]
我也遇到了相同的问题，联网功能完全用不了了，只有本地下载的可以看

**Comment by BreakFaith01** [comment]
啊没有啊，搜索还是可以用的，但是图片搜索没有用。

**Comment by Pitohui-Dichrous** [comment]
那坏事，我这是遇到什么问题了...

**Comment by xiaojieonly** [comment]
换成表站试试，可能是里站cookie过期了

**Comment by Jacfger** [comment]
我也有問題，重新登入也不行。不過表站能看

**Comment by 790854771wz** [comment]
集体出现这个情况不太正常吧，至于里站cookie过期也不太可能，我这开了另外一个版本的能进里站内容

**Comment by yi601** [comment]
你可以使用cookie重新登录，我用这个方法解决了这个问题。

**Comment by yi601** [comment]
你可以使用cookie重新登录，我用这个方法解决了与你相同的问题。

**Comment by BreakFaith01** [comment]
啊，你们是说图片搜索不能用的问题还是搜索不能用的问题:V

**Comment by BreakFaith01** [comment]
嗯，试过了，使用cookie重新登录依旧无法解决不能使用图片搜索的问题

**Comment by UjuiUjuMandan** [comment]
2024-02-11

- The "similarity scan" function for file searches has been disabled since the algorithm used can no longer scale with the size of the database. We'll be looking into if this can be replaced with a better performing lookup.
- 文件搜索的“相似性扫描”功能已被禁用，因为所使用的算法无法再随着数据库的大小而扩展。我们将研究是否可以用性能更好的查找来替代它。

https://e-hentai.org/news.php

**Comment by xiaojieonly** [comment]
感谢楼上，下一版会影藏图片搜索入口
