### ISSUE TITLE
能看预览图，打开却读取失败

### ISSUE THREAD

**Issue by tigerbroken** [xiaojieonly/Ehviewer_CN_SXJ#204]
如题，使用vpn后可以登录并且看预览的小图，但是打开以后显示读取失败，不知道是为什么，hosts打开和关闭都尝试过了![Screenshot_20220103_133445_com.xjs.ehviewer.jpg](https://user-images.githubusercontent.com/50123486/147902006-2cfbc160-4405-4346-aa3e-7e204e957039.jpg)![Screenshot_20220103_133436_com.xjs.ehviewer.jpg](https://user-images.githubusercontent.com/50123486/147902011-7f07c3ba-c6f9-40a9-8688-b893ff42b420.jpg)

**Comment by tigerbroken** [comment]
emmm，可能是解决了，方法是关掉下载原图(那么假如想打开下载原图应该怎么办)

**Comment by xiaojieonly** [comment]
弄个好点的网

**Comment by FengJunJie1** [comment]
> 

下载原图就显示读取失败 用的付费VPN，大概率不是网络的问题。

**Comment by ffeevv** [comment]
e站新机制，超过30天的画廊在高峰时段不能下载原图。
“2022-08-07

- Adjusted the "peak hours" used by original image downloading to better match the actual measured peak periods. It is now between 14:00 and 20:00 UTC Monday-Saturday, and between 05:00 and 20:00 UTC on Sundays. 

2022-06-07

A couple of minor tweaks to the "Download source image" changes, since it dropped the utilization by a lot more than we needed it to:

- It no longer applies to galleries posted in the last 7 30 days.

- It no longer applies for donators.


2022-06-06

- Using the "Download source image" function will now consume GP during peak hours. "Peak hours" for this purpose is (in UTC) weekdays between 14:00 and 20:00, and weekends between Saturday 14:00 until Sunday 20:00. This will also be used outside of peak hours if the image viewing limit is exhausted.

The GP cost is the same as what it would be for resetting the image limit, and also the same as the archiver cost for including it in an archive for a donator.

For database health reasons, this function will consume 1000 GP at a time, adding a "hidden" full image quota which is drawn from until it is exhausted.”

https://forums.e-hentai.org/index.php?showtopic=244935
